project:
  type: website
  pre-render:
    - "python tools/export_marimo.py"
    - "python tools/generate_categories.py"
  resources:
    # copy legacy HTML posts and their assets
    - post/*.html
    - post/*_files/**
    # other static files like favicon and images
    - static/**

website:
  title: "Aditya Mangal"
  site-url: https://www.adityamangal.com/
  google-analytics: UA-78062737-2
  comments: false
  navbar:
    logo: static/profile.jpg
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: https://github.com/adityamangal410
      - icon: twitter
        href: https://twitter.com/adityamangal410

format:
  html:
    theme: distill
    toc: true
    css: static/style.css
    include-after-body:
      - static/categories.html
      - static/disqus.html
filters:
  - marimo-team/marimo
