project:
  type: website

website:
  title: "Aditya Mangal's Blog"
  site-url: https://www.adityamangal.com/
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/adityamangal410
      - icon: twitter
        href: https://twitter.com/adityamangal410

format:
  html:
    theme: litera
    toc: true
