---
title: Music Artist Recommendation System - Surprise
author: Aditya Mangal
date: '2019-07-19'
slug: music-artist-recommendation-system-surprise
keywords:
  - tech
summary: Music Artist Recommendation System using the [Last.fm Dataset](https://grouplens.org/datasets/hetrec-2011/).
  Recommenders using Python's Surprise Library.
readingtime: '15'
draft: yes
coverImage: https://lh3.googleusercontent.com/PM_9k2f_aBF6_x5etgQpZzGNcQ6s8YgPVuFiVXqwcKZU3pmy9xsxvZcpb-NFZA7g9xFr38jJSwtiB_AMApLB7YHvK-imvjD31zSAGmRHB5Wk7h593uyZ48OD6suGUhG5B8Mi_hwqw-DLauTIaLSctW5JK9X4-rw2m0WOVf8kQRxG7GggWvyuD8gg0Dyy-AtER3AdMn2jG7upYXYs63MT940AHq826hq36vz2_c99_gUrFGDnnjsN4YnlpDFTYwzyjvglGJjtWzrGYnEZbLNvG9ifYxtzELvXhTtTYKwVAufOi-88g1OtLrddcBgN_izobnCesRnANY4abdcSNs5rkb9_BpYMJGA6_yPAkd1Bte7yDFeMzQ0myZW5MhW9tx5ZXyX5c59nqRpVwRbrrfkQxg2HxhZPjRNeirCe7oWsvcqJnp3rXIIkv74EaD2Hm37A55A1Orj8TXWyfPAA3Ixo-HOiU-uLt2EWQKCWRX6kia8457VlE_OHmnfIBdD7smvL5OVvZv0BNoTmnamiLJL7WvyZftfanwUQmfjiaXyvgBnk3RbROuBsFh6Ep4sVIza18RV_Ftc2EGIlxYH2wxUndUTvGMrnjC-hfIK_sEgCbvQup6-SSYe0iC7w5BvT5IXvmg2eFd99fiRxlVTqr1qfSWpp6AxmcbIEjQHRVaBvqeVn05XcCFO22ZYoFienq6JhyXu5X6TmoI1HA_PXPsDY4iCXfg=w2602-h1734-no
thumbnailImage: https://lh3.googleusercontent.com/4YYTtIHwN3Fo0ZO64A3_vTJd9sPnN-Gt4aC6Ae6D-4Ll3pUIkPy6L_0kzA_b1snFGWvOqlijjnB7q9VhkGsytIHtZquOl9iGZcNizV46_o4p7xUl_wvFT8wW4LAAf6TzkHD_lklURhCujLczN6VZgwtfLmPJgV4AARu-jv3uDAm2lOL1wJLx1fizS_D6Ta7L3dQTUBM5hS6zu5xNrXNTQC1oTNnFhoYSsKkoVmtiZQB-CblkHxWdWk1C7iT80u8GfWpGv91EszIErFxR7_reyzc5ATE3PYcXo_IND77hu8HfVShEDo6zLTknQwZ4sf8QvPcIRWAnd3skB0bXliz-ktFhrxzwJvmf92cmUgGCEVCh6bCF35ABoi5kZv3DXXwFDGVQp_LHzx1bbLRj1o22EeJKCry03tJx8gMB9mP2XBhpnMW9rA0UhneMXweqqUwh7R2JFJhI8C8MmgwMiatV_cxQeZhYvKOFqd9ALGuo9mhdCCdYhXfiYP-DthpwTS427F6LutIap8Ky_yUqy66Anm6x4xOG4pSrKSYMoIF-V9Hbg02clR7DrZrPatY0iNvsiFboP7pw-njBqv_lXMXS_9ca33IiuJ1ZcrHJeA8wLzjh_R9uuoWJjRp8XIoGNEapyLbLLITc9bYChyNiP9bPNldpD2tqMXNC6mY2i2_oe_NsRCoZvr1C_ZVgYCHTH6ufc-e2PcKVHsEYdF2uOKw4F95-VQ=w750-h500-no
thumbnailImagePosition: top
comments: no
coverCaption: Photo by Malte Wingen on Unsplash
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,error = FALSE)
```


# Introduction

Music Artist Recommendation System using the [Last.fm Dataset](https://grouplens.org/datasets/hetrec-2011/). Recommenders using Python's Surprise Library.

# Modelling

## Load Libraries
```{r}
rm(list = ls())
library(tidyverse)
library(tidylog)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(reticulate)

theme_set(theme_light())
# use_condaenv("py-portfolioV2")
use_condaenv("stanford-nlp")
```

## Obtain Data

```{r}
ratings <- read_csv("../data/hetrec2011-lastfm-2k/ratings_clean.csv")
ratings %>% 
  glimpse()
```

```{r}
ratings %>% 
  mutate(userID = as.factor(userID),
         artistID = as.factor(artistID)) -> ratings
ratings %>% 
  summary()
```

```{r}
friends <- read_csv("../data/hetrec2011-lastfm-2k/friends_clean.csv",
                    col_types = cols("userID" = col_factor(),
                                  "friendID" = col_factor()))
friends %>% 
  glimpse()
```

```{r}
metadata <- read_csv("../data/hetrec2011-lastfm-2k/metadata_clean.csv")
metadata %>% 
  mutate(userID = as.factor(userID),
         artistID = as.factor(artistID),
         tagID = as.factor(tagID),
         tagValue = as.factor(tagValue),
         artistName = as.factor(artistName)) -> metadata
```

```{r}
metadata %>% 
  glimpse()
```

```{r}
metadata %>% 
  group_by(artistID) %>% 
  summarise(num_tags = n_distinct(tagID)) %>% 
  arrange(desc(num_tags))
```

```{r}

```


# Python Surprise

```{python}
import surprise
from surprise import SVD, Dataset, Reader, accuracy
from surprise.model_selection import cross_validate, train_test_split
```

