---
title: Music Artist Recommendation System Project
author: Aditya Mangal
date: '2019-07-17'
categories:
  - Projects
tags:
  - Summary
slug: music-artist-recommendation-system-project
keywords:
  - tech
comments: false
showMeta: no
showActions: no
summary: Recommendation systems are all around us, from Netflix's amazing video recommender
  system to Amazon's product recommendation system and many many more. I have always
  been curious about the science and effort that goes into building one...
readingtime: '1'
coverImage: https://lh3.googleusercontent.com/zBdLyYOyVchcPZgxI6g4ONjGAOSsK3CcDitZq6_gHu1gbtmu5D_x-g5bZtweLd8gzAXYbIU9wIPpzG9l0bACOEKD59eETyU4vnmHqmCiLeGBRBXp3QVoh0RtSah9A28-5RHSKjgogkJM9HsFPR0_rG3wmfhntfk8y0FXMQ2sjWgQtV8_JU99JwCHpoRQqeZPa0pa5qRhczj3pDYgxciTf0ON97pfyvBaKTO1yh7sUl-_H-qJN703vJzlBwK-eqXIo7TTCqVUxsiLkFjQxMhHCOjAcoAmCEQaosSzkI3OVCexpyxhVi_P1GnKOkciC5XgVZadhLLXrHh3BSwEbQJWxXO7mu7qafLQQV4o8AwkiuOR6I4E3WobzWx5Ez8qhV2A8BLqOOJM-e2cnFV2ywAQWbxIXoZM3qyde30z4JZNFlRBS65UkPgncE_9R2rCCXRJOUBYgRP2u91io-6woH4sFyS-Z8FZVRiFDu7arZ3mI7l9jeVXqVEjvSw5go1Q52Irw0S_6t49Q_giN7eP_2mJ44lQVN_RpBquf-Nre0NkPpKXk4rph8lYPWLCVME84WCqIt6CQr7-RW_ZK7QnLOJ4dqwjGg6ipsgX6_ZnMDdJTDrpjwCUceMvB7myb_mbOMG_4BTA3WNOtrm7W6owMvcpNbTjr7Bakpb679hToV6V4l0kEKYn4k-b6QzTaKGrmL2_rvDUxlw5r2cB5ljl_wkZSYGF9w=w1464-h977-no
thumbnailImage: https://lh3.googleusercontent.com/eOBm_TsIFTmX18k2d5H3JbvrRoWKYKrkbRV94BiVpoOTvj4cAMQxKD9m5nhTSIR8al5xrzPVOEmsGnPh6UmXpAfQezwuuzhJdw1NlgYL9HnlXg4fhwNgJcFhU2lL8VQN8-bkTqxPJ9tJHnRKCEIyaFPJEZGa5woOy9IaM6JMaMsK7k5P67tY6-wXfLbvjKADTzfYrGVZ4QU4gWEoL5DZgRzXKBmRDnhTuQkVQeIRLEPKMFoSbwawyOjRKlqJRpblf-NHe2je2Dgst5wRrdBKHMOn8Juw199kRpINYBtuuPvyTEuS5jJqVrrRHajM007YmjA_YQ5LWW8bi6pVPOwam0Cvx_EP2oGE4Cd71B66XAic_MbRy_QgSqjs_hQuCUdnJvIcKyv0CGkt4_hflu4_I8fho76c_UM_hoU1ZkrP2Z1sc6BRepu_kW6HKg51gg-9c2VUQxp1SkX422ixEjstJAX8272wozq1eGoA-8eQ8q9tsfPqNa3KHqggvSM_2nkSVoSR22td6MK2Aaybdk9pJeX3exuQFmIhub9f-x6uqYgyzyrIUhfE5sy9ZBC99KSt0k97sy7gRtJsU4RFxDOa2wSfJJJi3F68RfLCyf138dSQl0JSjl55B4cqduiHIORWgt-knSj3otzgWHHF2V3wIvK9SfAe5svGiy629Th-H1NkrW6kNy5MG4Loh5xSxkIHDo7MzmDc5--ivFNv_XLhcj12Hg=w750-h500-no
thumbnailImagePosition: left
coverMeta: out
coverCaption: Photo by Mohammad Metri on Unsplash
---

# Project Summary

Recommendation systems are all around us, from Netflix's amazing video recommender system to Amazon's product recommendation system and many many more. I have always been curious about the science and effort that goes into building one and combining it with another one of my favorite topics, Music, would make it one of the more interesting projects that I try my hands on. Let's see if we can build a music artist recommendation system that is similar to the ones built by Spotify or Amazon Music. I will use the [Last.fm Dataset](https://grouplens.org/datasets/hetrec-2011/) provided by GroupLens and works towards building a music artist recommendation system.

# Project Goals

1. Exploratory data analysis of the Last.fm dataset.

2. Build Content-based and Collaborative filtering based recommendation system to recommend music artists to users.

3. Generate a hybrid recommender that combines all previously trained recommenders and provides recommendations. 

In the next series of posts I'll roughly follow the above steps.