---
title: House Buying in Hyd
author: Aditya Mangal
date: '2019-04-30'
categories:
  - Projects
tags:
  - DataAnalysis
  - DataScience
  - India
slug: arpit-house-buying
keywords:
  - tech
summary: House Buying Analysis in Hyd
readingtime: '15'
draft: yes
coverImage: https://lh3.googleusercontent.com/4lxMnTuwIwwJCORPTyGw2OuPUXpm5_2rCbHbvEdBw6GI0sc9JrOpgz0zSqDxOHiZM1yimQ4-EvfqcOmb866R3CXvkXC02zg1nQHGdaWD5JhU3smOkbrQKuGVwYQNR5jztwIXlhRfhicm6Agz7LvkMGmwxuDD6rdqHyDU9UXbNQRmqi0e4YQgECJuhj3JCrzqWcCQzxcMzeH2ph7tJe__Lbcv8HxZbW_XamTu7vns6RR-1GDw1-A9Jo6fFm1lvFmgEwjR425Tor7ZdZREOVFEoVhYTEVKUSX6cmpSnPVX7Z6pd25b0I2cnSpulJiw8022S4GqnKnsBHp5U8v_nUfpxHfR7f90yfaY5q0dMFUYovzmwdJO4iIWpcjQhkMwQwg0mwfvtY88Fw4lWbBbynN3RHfClbvwyAhwzcMWdqryCV2OchAbefSDIGnxUztvylrlJbK7m_L0e9zJIzF4f9zHqXTOkTl8-HWixn6-r6QgX2npbeadT1bkB97fx49MuBDu8ak5jOQRDmBDSGvdGVsYl5dexT9KMJI2aZw7N9GeSJpBEusWrTbrp-MCcN3nCnk0w2RtPO0VZumvoGZM5ALXn2qXxsyrqHUdtou-uvXpYFMgZvn8ZLtQsa0FJ5eahW0WH75mHIB0VnvCI2Px2C13fxYzLWMDsZVrgAzJ3_A6vOb0_QX5aOHtA5_VtWSgotNmyTq4rYyfhExlSJrYPHb8tvWrlQ=w2738-h1832-no
thumbnailImage: https://lh3.googleusercontent.com/IB30VrBzYpj_-HwXB366FBGwIi0l6a5yB-itcaSTWxn2AWfP37yvyOqb-DPC9euQy7iKDJTEOmOaJOCCuB8MD_fKgkevlyD6jgDidpjEP_0JyMwKi9C-N-ZdSa8qxEun8eaPG5ONcKImDoR95u9oqA1HGo2d2zWvqtPRr3CGQMR8qu0r9Ag-K8GKAHNw99JiwzbjSCwiOeQccF5xgg9NK_6V8Ot3mGhpDP86J2sIgUE5Q5Nfg8adWDpzKrGC3IHvNlOWEN6YKjEj1uKqBWSg0C_csN_BXYOZNcOxjyJn6fhNTf7iLOBToOB994gMYJ7382pIIhN1vs7bKljOJWTjhs1Gh2ks6k95iF7jSkYwARo7ONcYJbxy0kQ5F_YRiVNqi61lAYs4wbLb-6Bu9tPGoK7NtY_ALZ99cWVdWDmWdg6Hd64fyYkwNUUt3doYgApco6Tf1b2Qj9md6rp7avCsC_4hgs2iLncGpowFreXfP5i3M9w6AStWLPp4N14Oc5IA9GFLm4ohLn1ljRwMsk28R5_C8KgVp3Ur4ZViR6zePkybFNb_2GMkcbFTYPEs4kASlhCh2BTPOMLYT_KyeuFxD9OtAR5mWWsqzEq6JTw1TT1ZLA6qZ6hWlm52AF65AmCj4YEoEXCa7Qpst-39HrV22bqMTmL0bR4Du9_iDummpZ9Sh72yr-pjDeYOeKnpMwICIu7WDgI_A0R2S4Dt_AyGNks7Vw=w750-h502-no
thumbnailImagePosition: top
comments: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,error = FALSE)
```

# Introduction

House Buying Analysis in Hyd

# Analysis

## Load Libraries
```{r}
rm(list = ls())
library(tidyverse)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(janitor)

theme_set(theme_light())
```

```{r}
df <- read_csv("~/Downloads/House buying options - Sheet1.csv")
df
```

```{r}
df %>% 
  clean_names() %>% 
  select(-(x10:my_home_avtar)) %>% 
  filter(!is.na(final_score_aparna),
         final_score_aparna != "-") -> df
```

```{r}
df %>% 
  filter(weight_importance != "Total") -> df
df %>% 
  mutate(aparna_score = as.numeric(aparna_score),
         prestige_score = as.numeric(prestige_score),
         weight_importance = as.numeric(weight_importance),
         final_score_aparna = as.numeric(final_score_aparna),
         final_score_prestige = as.numeric(final_score_prestige),
         cost_factors = factor(cost_factors, cost_factors)) -> df
```
```{r}
df %>% 
  mutate(cost_factors = reorder(cost_factors, weight_importance)) %>% 
  ggplot( aes(x=cost_factors, y=weight_importance)) +
  geom_segment( aes(x=cost_factors, xend=cost_factors, y=0, yend=weight_importance), color="skyblue", size=1) +
  geom_point( color="blue", size=4, alpha=0.6) +
  coord_flip() + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position="none") +
  labs(x = "",
       y = "Weight Importance",
       title = "Cost Factor vs. Weight Importance",
       subtitle = "All cost factors",
       caption = "Based on data from House Buying Sheet") -> p1
p1
```

```{r}
df %>% 
  mutate(aparna_better_than_prestige = aparna_score/prestige_score,
         cost_factors = reorder(cost_factors, aparna_better_than_prestige)) %>% 
  ggplot( aes(x=cost_factors, y=aparna_better_than_prestige)) +
  geom_segment( aes(x=cost_factors, xend=cost_factors, y=0, yend=aparna_better_than_prestige), color="skyblue", size=1) +
  geom_point( color="blue", size=4, alpha=0.6) +
  coord_flip() + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position="none") +
  labs(x = "",
       y = "Aparna Score / Prestige Score",
       title = "Aparna Vs. Prestige Score",
       subtitle = "All cost factors",
       caption = "Based on data from House Buying Sheet") -> p2
p2
```

```{r fig.width=14, fig.height=8}
df %>% 
  mutate(aparna_better_than_prestige = final_score_aparna/final_score_prestige,
         cost_factors = reorder(cost_factors, weight_importance)) %>% 
  ggplot( aes(x=cost_factors, y=aparna_better_than_prestige)) +
  geom_segment( aes(x=cost_factors, xend=cost_factors, y=0, yend=aparna_better_than_prestige), color="skyblue", size=1) +
  geom_point( color="blue", size=4, alpha=0.6) +
  coord_flip() + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position="none") +
  labs(x = "",
       y = "Aparna Final Score / Prestige Final Score",
       title = "Aparna Vs. Prestige Final Score order by Weight Importance",
       subtitle = "All cost factors",
       caption = "Based on data from House Buying Sheet") -> p3

grid.arrange(p1, p3, ncol = 2)
```

```{r}
df %>% 
  select(-aparna_serene_park, -prestige_ivy_league, -criteria_for_idle_score) %>% 
  gather(key = "prop", value = "value", -cost_factors) %>% 
  spread(key = cost_factors, value = value) %>% 
  clean_names()
```


<sub><i>Cover Photo by Étienne Beauregard-Riverin on Unsplash</i></sub>