---
title: Music Artist Recommendation System - Surprise
author: Aditya Mangal
date: '2019-07-19'
slug: music-artist-recommendation-system-surprise
keywords:
  - tech
summary: Music Artist Recommendation System using the [Last.fm Dataset](https://grouplens.org/datasets/hetrec-2011/).
  Recommenders using Python's Surprise Library.
readingtime: '15'
draft: true
coverImage: https://lh3.googleusercontent.com/PM_9k2f_aBF6_x5etgQpZzGNcQ6s8YgPVuFiVXqwcKZU3pmy9xsxvZcpb-NFZA7g9xFr38jJSwtiB_AMApLB7YHvK-imvjD31zSAGmRHB5Wk7h593uyZ48OD6suGUhG5B8Mi_hwqw-DLauTIaLSctW5JK9X4-rw2m0WOVf8kQRxG7GggWvyuD8gg0Dyy-AtER3AdMn2jG7upYXYs63MT940AHq826hq36vz2_c99_gUrFGDnnjsN4YnlpDFTYwzyjvglGJjtWzrGYnEZbLNvG9ifYxtzELvXhTtTYKwVAufOi-88g1OtLrddcBgN_izobnCesRnANY4abdcSNs5rkb9_BpYMJGA6_yPAkd1Bte7yDFeMzQ0myZW5MhW9tx5ZXyX5c59nqRpVwRbrrfkQxg2HxhZPjRNeirCe7oWsvcqJnp3rXIIkv74EaD2Hm37A55A1Orj8TXWyfPAA3Ixo-HOiU-uLt2EWQKCWRX6kia8457VlE_OHmnfIBdD7smvL5OVvZv0BNoTmnamiLJL7WvyZftfanwUQmfjiaXyvgBnk3RbROuBsFh6Ep4sVIza18RV_Ftc2EGIlxYH2wxUndUTvGMrnjC-hfIK_sEgCbvQup6-SSYe0iC7w5BvT5IXvmg2eFd99fiRxlVTqr1qfSWpp6AxmcbIEjQHRVaBvqeVn05XcCFO22ZYoFienq6JhyXu5X6TmoI1HA_PXPsDY4iCXfg=w2602-h1734-no
thumbnailImage: https://lh3.googleusercontent.com/4YYTtIHwN3Fo0ZO64A3_vTJd9sPnN-Gt4aC6Ae6D-4Ll3pUIkPy6L_0kzA_b1snFGWvOqlijjnB7q9VhkGsytIHtZquOl9iGZcNizV46_o4p7xUl_wvFT8wW4LAAf6TzkHD_lklURhCujLczN6VZgwtfLmPJgV4AARu-jv3uDAm2lOL1wJLx1fizS_D6Ta7L3dQTUBM5hS6zu5xNrXNTQC1oTNnFhoYSsKkoVmtiZQB-CblkHxWdWk1C7iT80u8GfWpGv91EszIErFxR7_reyzc5ATE3PYcXo_IND77hu8HfVShEDo6zLTknQwZ4sf8QvPcIRWAnd3skB0bXliz-ktFhrxzwJvmf92cmUgGCEVCh6bCF35ABoi5kZv3DXXwFDGVQp_LHzx1bbLRj1o22EeJKCry03tJx8gMB9mP2XBhpnMW9rA0UhneMXweqqUwh7R2JFJhI8C8MmgwMiatV_cxQeZhYvKOFqd9ALGuo9mhdCCdYhXfiYP-DthpwTS427F6LutIap8Ky_yUqy66Anm6x4xOG4pSrKSYMoIF-V9Hbg02clR7DrZrPatY0iNvsiFboP7pw-njBqv_lXMXS_9ca33IiuJ1ZcrHJeA8wLzjh_R9uuoWJjRp8XIoGNEapyLbLLITc9bYChyNiP9bPNldpD2tqMXNC6mY2i2_oe_NsRCoZvr1C_ZVgYCHTH6ufc-e2PcKVHsEYdF2uOKw4F95-VQ=w750-h500-no
thumbnailImagePosition: top
coverCaption: Photo by Malte Wingen on Unsplash
format:
  html:
    theme: distill
freeze: true
output-file: music-artist-recommendation-system-surprise.html
---




# Introduction
<p>Music Artist Recommendation System using the <a href="https://grouplens.org/datasets/hetrec-2011/">Last.fm Dataset</a>. Recommenders using Python’s Surprise Library.</p>
# Modelling
## Load Libraries
<pre class="r"><code>rm(list = ls())
library(tidyverse)
library(tidylog)
library(lubridate)
library(ggplot2)
library(gridExtra)
library(reticulate)

theme_set(theme_light())
# use_condaenv(&quot;py-portfolioV2&quot;)
use_condaenv(&quot;stanford-nlp&quot;)</code></pre>
## Obtain Data
<pre class="r"><code>ratings &lt;- read_csv(&quot;../data/hetrec2011-lastfm-2k/ratings_clean.csv&quot;)
ratings %&gt;% 
  glimpse()</code></pre>
<pre><code>## Rows: 92,834
## Columns: 4
## $ userID   &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, …
## $ artistID &lt;dbl&gt; 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, …
## $ weight   &lt;dbl&gt; 13883, 11690, 11351, 10300, 8983, 6152, 5955, 4616, 4337, 41…
## $ rating   &lt;dbl&gt; 2.659038, 2.546706, 2.527479, 2.463997, 2.374611, 2.127279, …</code></pre>
<pre class="r"><code>ratings %&gt;% 
  mutate(userID = as.factor(userID),
         artistID = as.factor(artistID)) -&gt; ratings
ratings %&gt;% 
  summary()</code></pre>
<pre><code>##      userID         artistID         weight             rating        
##  2      :   50   89     :  611   Min.   :     1.0   Min.   :-3.57296  
##  3      :   50   289    :  522   1st Qu.:   107.0   1st Qu.:-0.51993  
##  4      :   50   288    :  484   Median :   260.0   Median : 0.06015  
##  5      :   50   227    :  480   Mean   :   745.2   Mean   : 0.00000  
##  6      :   50   300    :  473   3rd Qu.:   614.0   3rd Qu.: 0.62159  
##  7      :   50   67     :  429   Max.   :352698.0   Max.   : 4.77261  
##  (Other):92534   (Other):89835</code></pre>
<pre class="r"><code>friends &lt;- read_csv(&quot;../data/hetrec2011-lastfm-2k/friends_clean.csv&quot;,
                    col_types = cols(&quot;userID&quot; = col_factor(),
                                  &quot;friendID&quot; = col_factor()))
friends %&gt;% 
  glimpse()</code></pre>
<pre><code>## Rows: 25,434
## Columns: 2
## $ userID   &lt;fct&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, …
## $ friendID &lt;fct&gt; 275, 428, 515, 761, 831, 909, 1209, 1210, 1230, 1327, 1585, …</code></pre>
<pre class="r"><code>metadata &lt;- read_csv(&quot;../data/hetrec2011-lastfm-2k/metadata_clean.csv&quot;)
metadata %&gt;% 
  mutate(userID = as.factor(userID),
         artistID = as.factor(artistID),
         tagID = as.factor(tagID),
         tagValue = as.factor(tagValue),
         artistName = as.factor(artistName)) -&gt; metadata</code></pre>
<pre class="r"><code>metadata %&gt;% 
  glimpse()</code></pre>
<pre><code>## Rows: 186,479
## Columns: 8
## $ userID     &lt;fct&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ artistID   &lt;fct&gt; 52, 52, 52, 52, 52, 63, 63, 63, 63, 73, 73, 73, 73, 73, 73…
## $ tagID      &lt;fct&gt; 13, 15, 18, 21, 41, 13, 14, 23, 40, 13, 14, 15, 18, 20, 21…
## $ day        &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ month      &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…
## $ year       &lt;dbl&gt; 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009, 2009…
## $ tagValue   &lt;fct&gt; chillout, downtempo, electronic, trip-hop, female vovalist…
## $ artistName &lt;fct&gt; Morcheeba, Morcheeba, Morcheeba, Morcheeba, Morcheeba, Eni…</code></pre>
<pre class="r"><code>metadata %&gt;% 
  group_by(artistID) %&gt;% 
  summarise(num_tags = n_distinct(tagID)) %&gt;% 
  arrange(desc(num_tags))</code></pre>
<pre><code>## # A tibble: 12,523 x 2
##    artistID num_tags
##    &lt;fct&gt;       &lt;int&gt;
##  1 289           329
##  2 292           282
##  3 72            260
##  4 89            257
##  5 67            249
##  6 157           199
##  7 51            185
##  8 288           183
##  9 227           178
## 10 55            173
## # … with 12,513 more rows</code></pre>
# Python Surprise
<pre class="python"><code>import surprise
from surprise import SVD, Dataset, Reader, accuracy
from surprise.model_selection import cross_validate, train_test_split</code></pre>
